f = open(" /etc/yum.repos.d/doc.repo", "a")
f.write("[dvd1]")
f.write("\nname=dvd1")
f.write("\nbaseurl=file:///run/media/root/RHEL-8-0-0-BaseOS-x86_64/Appstream")
f.write("\ngpgcheck=0")
f.write("\n")
f.write("\n[dvd2]"
f.write("\nname=dvd2")
f.write("\nbaseurl=file:///run/media/root/RHEL-8-0-0-BaseOS-x86_64/BaseOS")
f.write("\ngpgcheck=0")
f.write("\n")
f.write("\n[docker-ce]")
f.write("\nname=docker")
f.write("\nbaseurl=http://download.docker.com/linux/centos/7/x86_64/stable")
f.write("\ngpgcheck=0")
f.close()